version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"

  go_app:
    build: .
    container_name: go_app
    restart: "no"
    depends_on:
      - mysql_db
    environment:
      - DB_HOST=mysql_db
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: "no"
    depends_on:
      - go_app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
