version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  users_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users_service
    working_dir: /app
    command: [/app/users_service]
    restart: "no"
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
    - .env 
    ports:
      - "8080"

  tasks_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasks_service
    working_dir: /app
    command: [/app/tasks_service]
    restart: "no"
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
    - .env 
    ports:
      - "8081"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: "no"
    depends_on:
      users_service:
        condition: service_started
      tasks_service:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      

